### ISSUE TITLE
Add Github topics to the repository

### ISSUE THREAD

**Issue by mendel5** [mendel5/finance-analysis-dkb#1]
Hi @GollyTicker , can you add the following Github topics to the repository at [https://github.com/GollyTicker/finance-analysis-dkb](https://github.com/GollyTicker/finance-analysis-dkb)?
* https://github.com/topics/dkb
* https://github.com/topics/banking
* https://github.com/topics/finance
* https://github.com/topics/personal-finance
* https://github.com/topics/germany

Thanks!

**Comment by GollyTicker** [comment]
Hey, thanks for the hint! I had not thought about it.

**Comment by mendel5** [comment]
Hi @GollyTicker , thank you for your quick feedback and for adding the topics!

Maybe you can activate issues for your repository as well? Then people can contribute more easily 🚀
You can do it by going to https://github.com/GollyTicker/finance-analysis-dkb/settings and activating the checkmark  ☑️  where it says `Issues`.

**Comment by GollyTicker** [comment]
Good point! I did that.

I'm surprised, that they are not there by default. I had just quickly published it without looking everywhere. I thought that issues are enable by default.
